### ISSUE TITLE
Train custom dataset

### ISSUE THREAD

**Issue by tiwari93** [princeton-nlp/DensePhrases#14]
Hi Jhyuklee,

Thank you for good works and support.
I have one query. Here I want use my custom pdf statements as a dump in place of Wikipedia dump, and want a model to get information from pdf data rather than getting it from wikipedia.

Do I need to freshly train our whole dump data or is there a way where I can fine tune this model based on checkpoints trained by you.

Pls guide.

**Comment by jhyuklee** [comment]
Hi @tiwari93,

You would first need to transform the pdf files into the json format as described [here](https://github.com/princeton-nlp/DensePhrases/tree/main/examples/create-custom-index).

Although it might depend on the domain of your text, I suggest first using the pre-trained DensePhrases to create a phrase index. Since DensePhrases was trained on the Wikipedia-style text, it will also work on the domain that is not that far from Wikipedia. You can use `densephrases-multi` to create your own phrase index and choose one of the query-side fine-tuned model (e.g., `densephrases-multi-query-multi` to retrieve phrases (or passages).

**Comment by tiwari93** [comment]
Thanks Jhyuklee,
I will try to do as suggested and update you for same.

**Comment by tiwari93** [comment]
@SAIVENKATARAJU That really great, i am in process of collecting dataset. However as suggested by @jhyuklee we need to create our own phrase index using densephrases-multi and then need to fine tune model as per mentioned on https://github.com/princeton-nlp/DensePhrases repository.

**Comment by jhyuklee** [comment]
Hi do you have any progress?
