### ISSUE TITLE
Issue while creating faiss index, Command is not clear 

### ISSUE THREAD

**Issue by SAIVENKATARAJU** [princeton-nlp/DensePhrases#15]
Hi,

What is the all in this command, I am getting unrecognized command error when i remove all.
```
python build_phrase_index.py \
    $SAVE_DIR/densephrases-multi_sample/dump all \
    --replace \
    --num_clusters 32 \
    --fine_quant OPQ96 \
    --doc_sample_ratio 1.0 \
    --vec_sample_ratio 1.0 \
    --cuda
```
I corrected  that by giving  --dump_dir before but its not creating anything. Please find the screenshot below,
![Screenshot from 2021-10-15 12-49-51](https://user-images.githubusercontent.com/46083296/137489498-ef6e99d2-c326-45f4-ae95-1f4c0e41665d.png)

**Comment by jhyuklee** [comment]
Hi @SAIVENKATARAJU, what is the version of faiss? Did you install faiss-gpu?
For the small version of phrase indexes, this shouldn't take more than several minutes.

**Comment by SAIVENKATARAJU** [comment]
Hi @jhyuklee 
I just debug the code further, and i got this error, Not sure what i am missing here. For debug purpose i have change the script and added arguments inside the code itself like this. Hope this will helpful. I am attaching my article.json here. 


```
args.dump_dir='./outputs/densephrases-multi_sample/dump'
args.stage='all'
args.replace=True
args.num_clusters=32
args.fine_quant='OPQ96'
args.doc_sample_ratio=1.0
args.vec_sample_ratio=1.0
args.cuda=True
args.index_filter=-1e8
args.index_name='start'
args.quantizer_path='quantizer.faiss'
args.trained_index_path='trained.faiss'
args.inv_path='merged.invdata'
args.subindex_name='index'
args.dump_paths='./densephrases-multi_sample/dump/phrase'
args.phrase_dir='phrase'
args.subindex_dir='./densephrases-multi_sample/dump/phrase/'
args.offset=0
args.norm_th=999
```


![Screenshot from 2021-10-16 15-56-52](https://user-images.githubusercontent.com/46083296/137594140-eff9f7e9-d231-4616-a869-e4e844a88827.png)

**Comment by jhyuklee** [comment]
Hi @SAIVENKATARAJU, I've downloaded your `article_original.json` and found out that the size of it is too small to train the index. I got the following error as follows:

```
RuntimeError: Error in void faiss::Clustering::train_encoded(faiss::Clustering::idx_t, const uint8_t*, const faiss::Index*, faiss::Index&, const float*) at /__w/faiss-wheels/faiss-wheels/faiss/faiss/Clustering.cpp:275: Error: 'nx >= k' failed: Number of training points (29) should be at least as large as number of clusters (256)
```

If you really want to build a phrase index for this small sized corpus, try exact search instead of IVFPQ.
This could be done by setting `--fine_quant none` for build_phrase_index. But this will also require you to fix the relevant parts in the `https://github.com/princeton-nlp/DensePhrases/blob/main/densephrases/index.py` because you will be using `faiss.IndexFlatIP` not `faiss.IndexIVFPQ.` So I suggest increasing the size of the corpus.

I didn't encounter any problem with `article.json` (default file). By the way, thanks for correcting the command for build_phrase_index.py.

**Comment by jhyuklee** [comment]
Hi @SAIVENKATARAJU, is your problem solved?

**Comment by SAIVENKATARAJU** [comment]
Hi ,
No Unfortunately, I am stuck with deadlock mentioned above. I am getting deadlock even for your articles.json. I saw your post on haystack. is there any near planning to integrate this to haystack?

**Comment by jhyuklee** [comment]
Yes, but that will take some time. I think there could be a problem with the faiss installation. You can try re-installing faiss and pytorch. Their dependencies sometimes conflict.

**Comment by jhyuklee** [comment]
Keep an eye on this issue if you need: https://github.com/deepset-ai/haystack/issues/1721
