### ISSUE TITLE
Train custom teacher model

### ISSUE THREAD

**Issue by light42** [princeton-nlp/DensePhrases#18]
Last night when I tried to train with custom pre-trained model I found out that densephrases also use another pre-trained model for cross-encoder, which is spanbert by default($TEACHER_MODEL).

When I tried to change it with bert-base-cased it failed to run. Can I change this or not? If I can, which model from huggingface I could use as teacher model?

**Comment by jhyuklee** [comment]
Hi, you can use the bert-base-cased models for your teacher as well. In fact, spanbert-base-cased has the exactly same architecture as bert-base-cased, so they can be replaced quite easily.

**Comment by light42** [comment]
Hi, sorry for late reply. I tested it and indeed it worked for bert-base-cased. But unfortunately I realized it couldn't work for Bart model because the limitations of transformers package installed for DensePhrases, and I could used roberta model as teacher model, but if I used it for run-rc-nq operations somehow it got error due to lack of keys on its dictionary.

So is that mean only spanbert/bert architecture that could be used for densephrases?

**Comment by jhyuklee** [comment]
Hi, it's good to hear that it worked. Whenever you use the teacher models, they need to have the same tokenizer as the student model since the distillation happens in the subword level. If you want to use RoBERTa, you would need to use RoBERTa student as well, which I was able to do so with current version of transformers (if not it will cause an error because RoBERTa and SpanBERT have different tokenizers). For BART, I'm not sure how you can do extractive QA + knowledge distillation.
